version: '3.4'

services:
    SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=StrongPassword@123# 
    WebApi:
        container_name: HealthTrackerContainer
        image: ${DOCKER_REGISTRY-}HealthTracker
        ports:
            - 8001:80 
        build:
          context: .
          dockerfile: HealthTracker/Dockerfile
        depends_on:
            - SqlServerDb