name: Build and deploy ASP.Net Core app to Azure Web App - HealthSyncBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore solHealthTracker/solHealthTracker.sln

      - name: Build with dotnet
        run: dotnet build solHealthTracker/solHealthTracker.sln --configuration Release

      - name: Publish with dotnet
        run: dotnet publish solHealthTracker/solHealthTracker.sln --configuration Release --output ${{ github.workspace }}/solHealthTracker/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/solHealthTracker/myapp
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.HealthSyncBackend_ADB1 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}